name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compilar el proyecto
      - name: Build the project
        run: npx tsc

      # 5. Configurar Docker CLI
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v2

      # 6. Autenticar en DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Construir y subir la imagen Docker
      - name: Build and push Docker image
        run: |
          docker build -t zerosworddev/resume-builder:develop .
          docker push zerosworddev/resume-builder:develop