
version: "3.8"

services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"  # Vite en desarrollo
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production