name: Push Docker Compose Images to DockerHub

on:
  push:
    branches:
      - develop
jobs:
  push-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker-compose build ./ -t 
      - name: Push Images to Docker Hub
        run: |
          docker push zerosworddev/resume-respaldo-2-server:latest
          docker push zerosworddev/resume-respaldo-2-client:latest