name: Push Docker Compose Images to DockerHub

on:
  push:
    branches:
      - develop

jobs:
  push-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images
        run: |
          docker-compose build server
          docker-compose build client

      - name: Push Images to Docker Hub
        run: |
          docker push zerosworddev/resume-respaldo-2-server:latest
          docker push zerosworddev/resume-respaldo-2-client:latest
