name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4


      # 2. Autenticar en DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construir y subir la imagen Docker
      - name: Build and push Docker image
        run: |
          docker tag zerosworddev/resume-builder:latest 
          docker push zerosworddev/resume-builder:latest